//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameters_master
    {
        public int ParameterID { get; set; }
        public int SetupTime { get; set; }
        public int OperatingTime { get; set; }
        public int PowerOnTime { get; set; }
        public Nullable<int> PartsCount { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
        public string AutoCutTime { get; set; }
        public string Total_CutTime { get; set; }
    }
}
