//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametermaster_view
    {
        public short ParameterID { get; set; }
        public short SetupTime { get; set; }
        public short OperatingTime { get; set; }
        public short PowerOnTime { get; set; }
        public short PartsCount { get; set; }
        public short InsertedOn { get; set; }
        public short MachineID { get; set; }
        public short Shift { get; set; }
        public short CorrectedDate { get; set; }
        public short InsertedOnTime { get; set; }
    }
}
